server:
  port: 8762
  
spring:
  application:
    name: springservice
  cloud:
    config:
      uri: http://ConfigServer:8888/
      profile: dev
      label: master
    
info:
  app:
    name: springservice-8762
  company:
    name: www.sele.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$

logging:
  config: classpath:log4j2-dev.xml
  level:
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN

eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 30
  instance-info-replication-interval-seconds: 24
  server:
    enable-self-preservation: false
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
    health:
      sensitive: false