/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sele.test;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

import org.bouncycastle.util.encoders.Base64;

public class App {


    public static void main(String[] args) throws Exception{
    	
    	BufferedReader  br = new BufferedReader(new FileReader(new File("d:/gfwlist.txt")));
    	BufferedWriter wr = new BufferedWriter(new FileWriter(new File("d:/gfw.txt")));
    	String content = null;
    	while((content = br.readLine())!=null) {
    		System.out.println("---------");
    		byte[] bytes = Base64.decode(content.getBytes());
    		wr.append(new String(bytes));
    	}
    	wr.flush();
    	wr.close();
    	br.close();
    	//byte[] bytes = Base64.decode("fHxmb250cy5nc3RhdGljLmNvbQpAQHx8c3NsLmdzdGF0aWMuY29tCkBAfHxoYW9z".getBytes());
    	
		

        
    }
}
